package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/plotarmordev/gitmoot/internal/artifact"
	"github.com/plotarmordev/gitmoot/internal/config"
	"github.com/plotarmordev/gitmoot/internal/db"
	"github.com/plotarmordev/gitmoot/internal/skillopt"
)

// Cross-repo pairwise round-trip E2E (#507/#508).
//
// Unlike the per-side tests in skillopt_pairwise_test.go (which hand-construct
// skillopt.PairwiseReviewPacket / PairwiseSecretMap Go structs and serialize
// them — i.e. they validate the importer against a shape the GO side assumes),
// this test drives the REAL `gitmoot skillopt pairwise import` over a fixture
// that was GENERATED by EXECUTING the gitmoot-skillopt fork's real emission code
// (gitmoot_skillopt/pairwise.py:run_pairwise_eval). See
// testdata/pairwise_roundtrip/{README.md,regen.py}. That closes the gap the two
// issues left open: each side was built against an assumed shared shape, never as
// one real producer->consumer round-trip.
//
// If the fork's emitted packet/secret-map shape and the Go importer disagree on
// a key name or value format (e.g. item_id, outputs[].label/response,
// champion_label/challenger_label, mapping[label]->promoted|candidate), the Go
// parser silently gets zero values, the unblind cannot resolve, items are
// skipped, the import exits non-zero, and these assertions FAIL — which is
// exactly the contract-shape mismatch this E2E exists to catch.
//
// SCOPE / what this does NOT catch: CI runs Go only and the fixture JSON is
// committed/frozen — `regen.py` is never run in CI. So this E2E validates the
// FROZEN fork-shape (as of the last manual regen) against the Go importer; it
// does NOT automatically catch a NEW fork-side shape change that lands without a
// regen of this fixture. The one drift axis we DO pin in CI without a regen is
// the contract version: TestSkillOptPairwiseRoundTripContractVersionPinned
// asserts the committed fixture's contract_version equals skillopt.ContractVersion,
// so a contract bump on either side that leaves the fixture stale turns red.
// When the fork's wire shape changes, re-run regen.py (see the testdata README).

const pairwiseRoundTripFixtureDir = "testdata/pairwise_roundtrip"

type pairwiseRoundTripExpectedItem struct {
	ItemID          string `json:"item_id"`
	Pick            string `json:"pick"`
	ExpectedWinner  string `json:"expected_winner"`
	PromotedOutput  string `json:"promoted_output"`
	CandidateOutput string `json:"candidate_output"`
}

type pairwiseRoundTripExpected struct {
	RunID          string                          `json:"run_id"`
	Source         string                          `json:"source"`
	FeedbackSource string                          `json:"feedback_source"`
	Items          []pairwiseRoundTripExpectedItem `json:"items"`
}

func loadPairwiseRoundTripExpected(t *testing.T) pairwiseRoundTripExpected {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(pairwiseRoundTripFixtureDir, "expected.json"))
	if err != nil {
		t.Fatalf("read expected.json: %v", err)
	}
	var exp pairwiseRoundTripExpected
	if err := json.Unmarshal(data, &exp); err != nil {
		t.Fatalf("decode expected.json: %v", err)
	}
	if len(exp.Items) == 0 {
		t.Fatalf("expected.json has no items")
	}
	return exp
}

func newPairwiseRoundTripHome(t *testing.T) (string, *db.Store, config.Paths) {
	t.Helper()
	home := t.TempDir()
	paths := config.PathsForHome(home)
	if err := config.Initialize(paths); err != nil {
		t.Fatalf("Initialize: %v", err)
	}
	store, err := db.Open(paths.Database)
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	t.Cleanup(func() { store.Close() })
	return home, store, paths
}

// optionBlob resolves the stored answer text for a given role ("champion" or
// "challenger") of an item: review option -> eval artifact -> blob bytes. This is
// what proves the UNBLIND JOIN end-to-end — the champion option must carry the
// promoted side's output, the challenger option the candidate's.
func optionBlob(t *testing.T, ctx context.Context, store *db.Store, paths config.Paths, runID, itemID, role string) string {
	t.Helper()
	options, err := store.ListEvalReviewOptions(ctx, runID, itemID)
	if err != nil {
		t.Fatalf("ListEvalReviewOptions(%s,%s): %v", runID, itemID, err)
	}
	var artifactID string
	for _, opt := range options {
		if opt.Role == role {
			artifactID = opt.ArtifactID
			break
		}
	}
	if artifactID == "" {
		t.Fatalf("no %q option for item %s (options: %+v)", role, itemID, options)
	}
	ea, err := store.GetEvalArtifact(ctx, artifactID)
	if err != nil {
		t.Fatalf("GetEvalArtifact(%s): %v", artifactID, err)
	}
	body, err := artifact.NewStore(paths.ArtifactBlobs).Read(ea.Hash)
	if err != nil {
		t.Fatalf("read blob %s: %v", ea.Hash, err)
	}
	return string(body)
}

// TestSkillOptPairwiseRoundTripImport is the cross-repo round-trip: it imports the
// FORK-GENERATED packet via the real CLI and asserts the import parses the fork's
// actual shape, unblinds each pick to the correct champion/challenger with the
// correct option join, sets the distinct live-pairwise source, and is idempotent.
func TestSkillOptPairwiseRoundTripImport(t *testing.T) {
	exp := loadPairwiseRoundTripExpected(t)
	home, store, paths := newPairwiseRoundTripHome(t)
	ctx := context.Background()
	runID := skillOptPairwiseRunIDPrefix + exp.RunID

	// Import the fork-generated packet directory (default file names).
	var stdout, stderr bytes.Buffer
	code := runSkillOptPairwise([]string{"import", pairwiseRoundTripFixtureDir, "--home", home, "--reviewer", "alice"}, &stdout, &stderr)
	if code != 0 {
		t.Fatalf("import of fork-generated packet exit = %d (want 0); stderr:\n%s\nstdout:\n%s", code, stderr.String(), stdout.String())
	}

	events, err := store.ListRankedFeedbackEvents(ctx, runID)
	if err != nil {
		t.Fatalf("ListRankedFeedbackEvents: %v", err)
	}
	if len(events) != len(exp.Items) {
		t.Fatalf("imported %d events, want %d (one per fork packet item)", len(events), len(exp.Items))
	}
	byItem := make(map[string]db.RankedFeedbackEvent, len(events))
	for _, ev := range events {
		byItem[ev.ItemID] = ev
	}

	for _, want := range exp.Items {
		ev, ok := byItem[want.ItemID]
		if !ok {
			t.Fatalf("no imported event for item %q", want.ItemID)
		}
		// Distinct live-pairwise source tag (separable from single-prompt Mode B).
		if ev.Source != skillOptPairwiseSource {
			t.Fatalf("item %s source = %q, want %q", want.ItemID, ev.Source, skillOptPairwiseSource)
		}
		if ev.Reviewer != "alice" {
			t.Fatalf("item %s reviewer = %q, want alice", want.ItemID, ev.Reviewer)
		}
		// UNBLINDING: the pick (a blinded A/B label) must resolve to the winner role
		// dictated by the fork's REAL secret map. An inverted unblind or a wrong join
		// makes this fail.
		if ev.Winner != want.ExpectedWinner {
			t.Fatalf("item %s winner = %q, want %q (pick %q against fork secret map)", want.ItemID, ev.Winner, want.ExpectedWinner, want.Pick)
		}

		// JOIN: the champion option must carry the promoted side's output and the
		// challenger option the candidate's — proving the unblind wires the right
		// fork output text under the right role, not merely the right label.
		if got := optionBlob(t, ctx, store, paths, runID, want.ItemID, "champion"); got != want.PromotedOutput {
			t.Fatalf("item %s champion option = %q, want promoted output %q", want.ItemID, got, want.PromotedOutput)
		}
		if got := optionBlob(t, ctx, store, paths, runID, want.ItemID, "challenger"); got != want.CandidateOutput {
			t.Fatalf("item %s challenger option = %q, want candidate output %q", want.ItemID, got, want.CandidateOutput)
		}
	}

	// Distinct feedback_source recorded on the run metadata.
	run, err := store.GetEvalRun(ctx, runID)
	if err != nil {
		t.Fatalf("GetEvalRun: %v", err)
	}
	var meta map[string]any
	if err := json.Unmarshal([]byte(run.MetadataJSON), &meta); err != nil {
		t.Fatalf("decode run metadata: %v", err)
	}
	if meta["feedback_source"] != skillOptPairwiseFeedbackSource {
		t.Fatalf("run feedback_source = %v, want %q", meta["feedback_source"], skillOptPairwiseFeedbackSource)
	}

	// Idempotency: re-importing the same reviewed packet must not double-count.
	for i := 0; i < 2; i++ {
		var so, se bytes.Buffer
		if c := runSkillOptPairwise([]string{"import", pairwiseRoundTripFixtureDir, "--home", home, "--reviewer", "alice"}, &so, &se); c != 0 {
			t.Fatalf("re-import %d exit = %d; stderr: %s", i, c, se.String())
		}
	}
	again, err := store.ListRankedFeedbackEvents(ctx, runID)
	if err != nil {
		t.Fatalf("ListRankedFeedbackEvents after re-import: %v", err)
	}
	if len(again) != len(exp.Items) {
		t.Fatalf("after 3 imports events = %d, want %d (idempotent, no double count)", len(again), len(exp.Items))
	}
}

// TestSkillOptPairwiseRoundTripDetectsShapeDrift proves the round-trip GENUINELY
// fails when the fork packet shape and the Go importer disagree. It copies the
// fork-generated fixture and renames the secret map's `champion_label` /
// `challenger_label` keys (simulating a fork-side key drift). The Go parser then
// reads empty labels, the unblind cannot resolve, every item is skipped, the
// import exits non-zero, and nothing is persisted — the failure mode this E2E
// exists to surface.
func TestSkillOptPairwiseRoundTripDetectsShapeDrift(t *testing.T) {
	exp := loadPairwiseRoundTripExpected(t)
	home, store, _ := newPairwiseRoundTripHome(t)
	ctx := context.Background()

	dir := t.TempDir()
	for _, name := range []string{pairwisePacketFileName, pairwiseSecretMapFileName, pairwisePicksFileName} {
		data, err := os.ReadFile(filepath.Join(pairwiseRoundTripFixtureDir, name))
		if err != nil {
			t.Fatalf("read fixture %s: %v", name, err)
		}
		if name == pairwiseSecretMapFileName {
			// Simulate a fork-side contract key rename that the Go importer does not
			// know about. The labels become invisible to the parser.
			s := string(data)
			s = strings.ReplaceAll(s, "\"champion_label\"", "\"championLabel\"")
			s = strings.ReplaceAll(s, "\"challenger_label\"", "\"challengerLabel\"")
			// Also drop the mapping so the labels are the only unblind source, making
			// the drift unrecoverable (mirrors a real shape mismatch on these keys).
			s = strings.ReplaceAll(s, "\"mapping\"", "\"mappingRenamed\"")
			data = []byte(s)
		}
		if err := os.WriteFile(filepath.Join(dir, name), data, 0o644); err != nil {
			t.Fatalf("write tampered %s: %v", name, err)
		}
	}

	var stdout, stderr bytes.Buffer
	code := runSkillOptPairwise([]string{"import", dir, "--home", home}, &stdout, &stderr)
	if code == 0 {
		t.Fatalf("import of shape-drifted packet exit = 0, want non-zero (the mismatch must be caught); stdout:\n%s", stdout.String())
	}

	runID := skillOptPairwiseRunIDPrefix + exp.RunID
	events, err := store.ListRankedFeedbackEvents(ctx, runID)
	if err != nil {
		t.Fatalf("ListRankedFeedbackEvents: %v", err)
	}
	if len(events) != 0 {
		t.Fatalf("shape-drifted import persisted %d events, want 0", len(events))
	}
}

// TestSkillOptPairwiseRoundTripContractVersionPinned pins the ONE drift axis this
// Go-only, frozen-fixture E2E can guard in CI without re-running regen.py: the
// contract version. CI never executes the fork's regen.py, so if the fork (or the
// Go side) bumps the contract version and this committed fixture is NOT
// regenerated, the round-trip would otherwise stay green against a stale shape.
// Asserting the committed packet/secret-map contract_version equals the Go
// skillopt.ContractVersion constant turns that staleness red: a bump on either
// side without a matching regen of this fixture fails here. (The fork emits these
// integers; this is a real fork->Go value, not a hand-authored Go assumption.)
func TestSkillOptPairwiseRoundTripContractVersionPinned(t *testing.T) {
	type versioned struct {
		ContractVersion int `json:"contract_version"`
	}
	for _, name := range []string{pairwisePacketFileName, pairwiseSecretMapFileName} {
		data, err := os.ReadFile(filepath.Join(pairwiseRoundTripFixtureDir, name))
		if err != nil {
			t.Fatalf("read fixture %s: %v", name, err)
		}
		var v versioned
		if err := json.Unmarshal(data, &v); err != nil {
			t.Fatalf("decode %s: %v", name, err)
		}
		if v.ContractVersion != skillopt.ContractVersion {
			t.Fatalf("fixture %s contract_version = %d, want %d (skillopt.ContractVersion); "+
				"a contract bump without re-running regen.py left this fixture stale — "+
				"regenerate it (see testdata/pairwise_roundtrip/README.md)",
				name, v.ContractVersion, skillopt.ContractVersion)
		}
	}
}
